// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package server

import (
	"sync"
)

// Ensure, that SearchTriggerMock does implement SearchTrigger.
// If this is not the case, regenerate this file with moq.
var _ SearchTrigger = &SearchTriggerMock{}

// SearchTriggerMock is a mock implementation of SearchTrigger.
//
//	func TestSomethingThatUsesSearchTrigger(t *testing.T) {
//
//		// make and configure a mocked SearchTrigger
//		mockedSearchTrigger := &SearchTriggerMock{
//			TriggerFunc: func()  {
//				panic("mock out the Trigger method")
//			},
//		}
//
//		// use mockedSearchTrigger in code that requires SearchTrigger
//		// and then make assertions.
//
//	}
type SearchTriggerMock struct {
	// TriggerFunc mocks the Trigger method.
	TriggerFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Trigger holds details about calls to the Trigger method.
		Trigger []struct {
		}
	}
	lockTrigger sync.RWMutex
}

// Trigger calls TriggerFunc.
func (mock *SearchTriggerMock) Trigger() {
	callInfo := struct {
	}{}
	mock.lockTrigger.Lock()
	mock.calls.Trigger = append(mock.calls.Trigger, callInfo)
	mock.lockTrigger.Unlock()
	if mock.TriggerFunc == nil {
		return
	}
	mock.TriggerFunc()
}

// TriggerCalls gets all the calls that were made to Trigger.
// Check the length with:
//
//	len(mockedSearchTrigger.TriggerCalls())
func (mock *SearchTriggerMock) TriggerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTrigger.RLock()
	calls = mock.calls.Trigger
	mock.lockTrigger.RUnlock()
	return calls
}
