// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package email

import (
	"sync"

	emailCore "github.com/oxynote/oxynote/server/core/internal/email"
)

// Ensure, that SenderMock does implement Sender.
// If this is not the case, regenerate this file with moq.
var _ Sender = &SenderMock{}

// SenderMock is a mock implementation of Sender.
//
//	func TestSomethingThatUsesSender(t *testing.T) {
//
//		// make and configure a mocked Sender
//		mockedSender := &SenderMock{
//			SendFunc: func(tmpl emailCore.Template, d emailCore.Data) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedSender in code that requires Sender
//		// and then make assertions.
//
//	}
type SenderMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(tmpl emailCore.Template, d emailCore.Data) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Tmpl is the tmpl argument value.
			Tmpl emailCore.Template
			// D is the d argument value.
			D emailCore.Data
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *SenderMock) Send(tmpl emailCore.Template, d emailCore.Data) error {
	callInfo := struct {
		Tmpl emailCore.Template
		D    emailCore.Data
	}{
		Tmpl: tmpl,
		D:    d,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	if mock.SendFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.SendFunc(tmpl, d)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedSender.SendCalls())
func (mock *SenderMock) SendCalls() []struct {
	Tmpl emailCore.Template
	D    emailCore.Data
} {
	var calls []struct {
		Tmpl emailCore.Template
		D    emailCore.Data
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
