// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package manager

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/search"
	"github.com/rs/xid"
)

// Ensure, that IndexMock does implement Index.
// If this is not the case, regenerate this file with moq.
var _ Index = &IndexMock{}

// IndexMock is a mock implementation of Index.
//
//	func TestSomethingThatUsesIndex(t *testing.T) {
//
//		// make and configure a mocked Index
//		mockedIndex := &IndexMock{
//			DeleteBranchFunc: func(ctx context.Context, branchID xid.ID) error {
//				panic("mock out the DeleteBranch method")
//			},
//			DeleteDocumentFunc: func(ctx context.Context, documentID xid.ID) error {
//				panic("mock out the DeleteDocument method")
//			},
//			DeleteOrganizationFunc: func(ctx context.Context, organizationID string) error {
//				panic("mock out the DeleteOrganization method")
//			},
//			ReplaceBranchFunc: func(ctx context.Context, branchID xid.ID, entries map[string]search.Block) error {
//				panic("mock out the ReplaceBranch method")
//			},
//		}
//
//		// use mockedIndex in code that requires Index
//		// and then make assertions.
//
//	}
type IndexMock struct {
	// DeleteBranchFunc mocks the DeleteBranch method.
	DeleteBranchFunc func(ctx context.Context, branchID xid.ID) error

	// DeleteDocumentFunc mocks the DeleteDocument method.
	DeleteDocumentFunc func(ctx context.Context, documentID xid.ID) error

	// DeleteOrganizationFunc mocks the DeleteOrganization method.
	DeleteOrganizationFunc func(ctx context.Context, organizationID string) error

	// ReplaceBranchFunc mocks the ReplaceBranch method.
	ReplaceBranchFunc func(ctx context.Context, branchID xid.ID, entries map[string]search.Block) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteBranch holds details about calls to the DeleteBranch method.
		DeleteBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BranchID is the branchID argument value.
			BranchID xid.ID
		}
		// DeleteDocument holds details about calls to the DeleteDocument method.
		DeleteDocument []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
		}
		// DeleteOrganization holds details about calls to the DeleteOrganization method.
		DeleteOrganization []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// ReplaceBranch holds details about calls to the ReplaceBranch method.
		ReplaceBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BranchID is the branchID argument value.
			BranchID xid.ID
			// Entries is the entries argument value.
			Entries map[string]search.Block
		}
	}
	lockDeleteBranch       sync.RWMutex
	lockDeleteDocument     sync.RWMutex
	lockDeleteOrganization sync.RWMutex
	lockReplaceBranch      sync.RWMutex
}

// DeleteBranch calls DeleteBranchFunc.
func (mock *IndexMock) DeleteBranch(ctx context.Context, branchID xid.ID) error {
	callInfo := struct {
		Ctx      context.Context
		BranchID xid.ID
	}{
		Ctx:      ctx,
		BranchID: branchID,
	}
	mock.lockDeleteBranch.Lock()
	mock.calls.DeleteBranch = append(mock.calls.DeleteBranch, callInfo)
	mock.lockDeleteBranch.Unlock()
	if mock.DeleteBranchFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteBranchFunc(ctx, branchID)
}

// DeleteBranchCalls gets all the calls that were made to DeleteBranch.
// Check the length with:
//
//	len(mockedIndex.DeleteBranchCalls())
func (mock *IndexMock) DeleteBranchCalls() []struct {
	Ctx      context.Context
	BranchID xid.ID
} {
	var calls []struct {
		Ctx      context.Context
		BranchID xid.ID
	}
	mock.lockDeleteBranch.RLock()
	calls = mock.calls.DeleteBranch
	mock.lockDeleteBranch.RUnlock()
	return calls
}

// DeleteDocument calls DeleteDocumentFunc.
func (mock *IndexMock) DeleteDocument(ctx context.Context, documentID xid.ID) error {
	callInfo := struct {
		Ctx        context.Context
		DocumentID xid.ID
	}{
		Ctx:        ctx,
		DocumentID: documentID,
	}
	mock.lockDeleteDocument.Lock()
	mock.calls.DeleteDocument = append(mock.calls.DeleteDocument, callInfo)
	mock.lockDeleteDocument.Unlock()
	if mock.DeleteDocumentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteDocumentFunc(ctx, documentID)
}

// DeleteDocumentCalls gets all the calls that were made to DeleteDocument.
// Check the length with:
//
//	len(mockedIndex.DeleteDocumentCalls())
func (mock *IndexMock) DeleteDocumentCalls() []struct {
	Ctx        context.Context
	DocumentID xid.ID
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID xid.ID
	}
	mock.lockDeleteDocument.RLock()
	calls = mock.calls.DeleteDocument
	mock.lockDeleteDocument.RUnlock()
	return calls
}

// DeleteOrganization calls DeleteOrganizationFunc.
func (mock *IndexMock) DeleteOrganization(ctx context.Context, organizationID string) error {
	callInfo := struct {
		Ctx            context.Context
		OrganizationID string
	}{
		Ctx:            ctx,
		OrganizationID: organizationID,
	}
	mock.lockDeleteOrganization.Lock()
	mock.calls.DeleteOrganization = append(mock.calls.DeleteOrganization, callInfo)
	mock.lockDeleteOrganization.Unlock()
	if mock.DeleteOrganizationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteOrganizationFunc(ctx, organizationID)
}

// DeleteOrganizationCalls gets all the calls that were made to DeleteOrganization.
// Check the length with:
//
//	len(mockedIndex.DeleteOrganizationCalls())
func (mock *IndexMock) DeleteOrganizationCalls() []struct {
	Ctx            context.Context
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		OrganizationID string
	}
	mock.lockDeleteOrganization.RLock()
	calls = mock.calls.DeleteOrganization
	mock.lockDeleteOrganization.RUnlock()
	return calls
}

// ReplaceBranch calls ReplaceBranchFunc.
func (mock *IndexMock) ReplaceBranch(ctx context.Context, branchID xid.ID, entries map[string]search.Block) error {
	callInfo := struct {
		Ctx      context.Context
		BranchID xid.ID
		Entries  map[string]search.Block
	}{
		Ctx:      ctx,
		BranchID: branchID,
		Entries:  entries,
	}
	mock.lockReplaceBranch.Lock()
	mock.calls.ReplaceBranch = append(mock.calls.ReplaceBranch, callInfo)
	mock.lockReplaceBranch.Unlock()
	if mock.ReplaceBranchFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ReplaceBranchFunc(ctx, branchID, entries)
}

// ReplaceBranchCalls gets all the calls that were made to ReplaceBranch.
// Check the length with:
//
//	len(mockedIndex.ReplaceBranchCalls())
func (mock *IndexMock) ReplaceBranchCalls() []struct {
	Ctx      context.Context
	BranchID xid.ID
	Entries  map[string]search.Block
} {
	var calls []struct {
		Ctx      context.Context
		BranchID xid.ID
		Entries  map[string]search.Block
	}
	mock.lockReplaceBranch.RLock()
	calls = mock.calls.ReplaceBranch
	mock.lockReplaceBranch.RUnlock()
	return calls
}
