// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tools

import (
	"context"
	"sync"

	"github.com/oxynote/oxynote/server/core/internal/document"
	"github.com/oxynote/oxynote/server/core/internal/search"
	"github.com/rs/xid"
)

// Ensure, that TxMock does implement Tx.
// If this is not the case, regenerate this file with moq.
var _ Tx = &TxMock{}

// TxMock is a mock implementation of Tx.
//
//	func TestSomethingThatUsesTx(t *testing.T) {
//
//		// make and configure a mocked Tx
//		mockedTx := &TxMock{
//			CommitFunc: func() error {
//				panic("mock out the Commit method")
//			},
//			DeleteDocumentFunc: func(ctx context.Context, id xid.ID, organizationID string) ([]xid.ID, error) {
//				panic("mock out the DeleteDocument method")
//			},
//			InsertDocumentFunc: func(ctx context.Context, doc document.Document) error {
//				panic("mock out the InsertDocument method")
//			},
//			InsertSearchJobFunc: func(ctx context.Context, job search.Job) error {
//				panic("mock out the InsertSearchJob method")
//			},
//			RollbackFunc: func() error {
//				panic("mock out the Rollback method")
//			},
//			UpsertDocumentMaintainersFunc: func(ctx context.Context, documentID xid.ID, organizationID string, maintainerIDs []string) error {
//				panic("mock out the UpsertDocumentMaintainers method")
//			},
//		}
//
//		// use mockedTx in code that requires Tx
//		// and then make assertions.
//
//	}
type TxMock struct {
	// CommitFunc mocks the Commit method.
	CommitFunc func() error

	// DeleteDocumentFunc mocks the DeleteDocument method.
	DeleteDocumentFunc func(ctx context.Context, id xid.ID, organizationID string) ([]xid.ID, error)

	// InsertDocumentFunc mocks the InsertDocument method.
	InsertDocumentFunc func(ctx context.Context, doc document.Document) error

	// InsertSearchJobFunc mocks the InsertSearchJob method.
	InsertSearchJobFunc func(ctx context.Context, job search.Job) error

	// RollbackFunc mocks the Rollback method.
	RollbackFunc func() error

	// UpsertDocumentMaintainersFunc mocks the UpsertDocumentMaintainers method.
	UpsertDocumentMaintainersFunc func(ctx context.Context, documentID xid.ID, organizationID string, maintainerIDs []string) error

	// calls tracks calls to the methods.
	calls struct {
		// Commit holds details about calls to the Commit method.
		Commit []struct {
		}
		// DeleteDocument holds details about calls to the DeleteDocument method.
		DeleteDocument []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
		}
		// InsertDocument holds details about calls to the InsertDocument method.
		InsertDocument []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Doc is the doc argument value.
			Doc document.Document
		}
		// InsertSearchJob holds details about calls to the InsertSearchJob method.
		InsertSearchJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Job is the job argument value.
			Job search.Job
		}
		// Rollback holds details about calls to the Rollback method.
		Rollback []struct {
		}
		// UpsertDocumentMaintainers holds details about calls to the UpsertDocumentMaintainers method.
		UpsertDocumentMaintainers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID xid.ID
			// OrganizationID is the organizationID argument value.
			OrganizationID string
			// MaintainerIDs is the maintainerIDs argument value.
			MaintainerIDs []string
		}
	}
	lockCommit                    sync.RWMutex
	lockDeleteDocument            sync.RWMutex
	lockInsertDocument            sync.RWMutex
	lockInsertSearchJob           sync.RWMutex
	lockRollback                  sync.RWMutex
	lockUpsertDocumentMaintainers sync.RWMutex
}

// Commit calls CommitFunc.
func (mock *TxMock) Commit() error {
	callInfo := struct {
	}{}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	if mock.CommitFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CommitFunc()
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedTx.CommitCalls())
func (mock *TxMock) CommitCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// DeleteDocument calls DeleteDocumentFunc.
func (mock *TxMock) DeleteDocument(ctx context.Context, id xid.ID, organizationID string) ([]xid.ID, error) {
	callInfo := struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}{
		Ctx:            ctx,
		ID:             id,
		OrganizationID: organizationID,
	}
	mock.lockDeleteDocument.Lock()
	mock.calls.DeleteDocument = append(mock.calls.DeleteDocument, callInfo)
	mock.lockDeleteDocument.Unlock()
	if mock.DeleteDocumentFunc == nil {
		var (
			iDsOut []xid.ID
			errOut error
		)
		return iDsOut, errOut
	}
	return mock.DeleteDocumentFunc(ctx, id, organizationID)
}

// DeleteDocumentCalls gets all the calls that were made to DeleteDocument.
// Check the length with:
//
//	len(mockedTx.DeleteDocumentCalls())
func (mock *TxMock) DeleteDocumentCalls() []struct {
	Ctx            context.Context
	ID             xid.ID
	OrganizationID string
} {
	var calls []struct {
		Ctx            context.Context
		ID             xid.ID
		OrganizationID string
	}
	mock.lockDeleteDocument.RLock()
	calls = mock.calls.DeleteDocument
	mock.lockDeleteDocument.RUnlock()
	return calls
}

// InsertDocument calls InsertDocumentFunc.
func (mock *TxMock) InsertDocument(ctx context.Context, doc document.Document) error {
	callInfo := struct {
		Ctx context.Context
		Doc document.Document
	}{
		Ctx: ctx,
		Doc: doc,
	}
	mock.lockInsertDocument.Lock()
	mock.calls.InsertDocument = append(mock.calls.InsertDocument, callInfo)
	mock.lockInsertDocument.Unlock()
	if mock.InsertDocumentFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertDocumentFunc(ctx, doc)
}

// InsertDocumentCalls gets all the calls that were made to InsertDocument.
// Check the length with:
//
//	len(mockedTx.InsertDocumentCalls())
func (mock *TxMock) InsertDocumentCalls() []struct {
	Ctx context.Context
	Doc document.Document
} {
	var calls []struct {
		Ctx context.Context
		Doc document.Document
	}
	mock.lockInsertDocument.RLock()
	calls = mock.calls.InsertDocument
	mock.lockInsertDocument.RUnlock()
	return calls
}

// InsertSearchJob calls InsertSearchJobFunc.
func (mock *TxMock) InsertSearchJob(ctx context.Context, job search.Job) error {
	callInfo := struct {
		Ctx context.Context
		Job search.Job
	}{
		Ctx: ctx,
		Job: job,
	}
	mock.lockInsertSearchJob.Lock()
	mock.calls.InsertSearchJob = append(mock.calls.InsertSearchJob, callInfo)
	mock.lockInsertSearchJob.Unlock()
	if mock.InsertSearchJobFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.InsertSearchJobFunc(ctx, job)
}

// InsertSearchJobCalls gets all the calls that were made to InsertSearchJob.
// Check the length with:
//
//	len(mockedTx.InsertSearchJobCalls())
func (mock *TxMock) InsertSearchJobCalls() []struct {
	Ctx context.Context
	Job search.Job
} {
	var calls []struct {
		Ctx context.Context
		Job search.Job
	}
	mock.lockInsertSearchJob.RLock()
	calls = mock.calls.InsertSearchJob
	mock.lockInsertSearchJob.RUnlock()
	return calls
}

// Rollback calls RollbackFunc.
func (mock *TxMock) Rollback() error {
	callInfo := struct {
	}{}
	mock.lockRollback.Lock()
	mock.calls.Rollback = append(mock.calls.Rollback, callInfo)
	mock.lockRollback.Unlock()
	if mock.RollbackFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RollbackFunc()
}

// RollbackCalls gets all the calls that were made to Rollback.
// Check the length with:
//
//	len(mockedTx.RollbackCalls())
func (mock *TxMock) RollbackCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRollback.RLock()
	calls = mock.calls.Rollback
	mock.lockRollback.RUnlock()
	return calls
}

// UpsertDocumentMaintainers calls UpsertDocumentMaintainersFunc.
func (mock *TxMock) UpsertDocumentMaintainers(ctx context.Context, documentID xid.ID, organizationID string, maintainerIDs []string) error {
	callInfo := struct {
		Ctx            context.Context
		DocumentID     xid.ID
		OrganizationID string
		MaintainerIDs  []string
	}{
		Ctx:            ctx,
		DocumentID:     documentID,
		OrganizationID: organizationID,
		MaintainerIDs:  maintainerIDs,
	}
	mock.lockUpsertDocumentMaintainers.Lock()
	mock.calls.UpsertDocumentMaintainers = append(mock.calls.UpsertDocumentMaintainers, callInfo)
	mock.lockUpsertDocumentMaintainers.Unlock()
	if mock.UpsertDocumentMaintainersFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpsertDocumentMaintainersFunc(ctx, documentID, organizationID, maintainerIDs)
}

// UpsertDocumentMaintainersCalls gets all the calls that were made to UpsertDocumentMaintainers.
// Check the length with:
//
//	len(mockedTx.UpsertDocumentMaintainersCalls())
func (mock *TxMock) UpsertDocumentMaintainersCalls() []struct {
	Ctx            context.Context
	DocumentID     xid.ID
	OrganizationID string
	MaintainerIDs  []string
} {
	var calls []struct {
		Ctx            context.Context
		DocumentID     xid.ID
		OrganizationID string
		MaintainerIDs  []string
	}
	mock.lockUpsertDocumentMaintainers.RLock()
	calls = mock.calls.UpsertDocumentMaintainers
	mock.lockUpsertDocumentMaintainers.RUnlock()
	return calls
}
